# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ks_KkjOuGnTrUhN6eVzJ1nTk23wz4Pap
"""



#read and write the data-r+
filed=open("guru","r+")
filed.write("hii\nhow are you\niam fine\nhave a nice day")
filed.seek(0)
p=filed.read()
print(p)
filed.close()

#read and write the data-w+
sea=open("rear","w+")
sea.write("blue is my favourite colour,,,\nblue is a mild colour\nsea is the best blue thing")
sea.seek(0)
pr=sea.read()
print(pr)

#read and write the data-w+
#If the file does not exist, r+ throws FileNotFoundError; the w+ creates the file
fear=open("red.txt","w+")
fear.write("red is a colour of danger and violence!!!")
fear.seek(0)
print(fear.read())

#read,append and write the data-a+
filed=open("guru","a+")
filed.write("\nhave faith!!!\nYOU CAN DO IT!!!")
filed.seek(0)
p=filed.read()
print(p)
filed.close()